### ISSUE TITLE
path referencing a windows environment variable containing multiple paths, parsing error

### ISSUE THREAD

**Issue by raxuser100** [ueffel/Keypirinha-Git#1]
Great tool, thanks for developing it!

Noticed a small error on Windows 11, when an enviroment variable contains multiple paths:

```
10:24:57.283 ** ERROR: Error from Git.Git.on_execute: <class 'OSError'>: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\WorkArea\\developer\\code;d:\\temp'
Traceback (most recent call last):
  File "C:\apps\keypirinha\portable\Profile\InstalledPackages\Git.keypirinha-package\git.py", line 404, in on_execute
  File "C:\apps\keypirinha\portable\Profile\InstalledPackages\Git.keypirinha-package\git.py", line 187, in _rescan
  File "C:\apps\keypirinha\portable\Profile\InstalledPackages\Git.keypirinha-package\git.py", line 163, in _scan_path
```
The ini file settings:

```
[main]
[scan_path/SpacebandsStuff]
paths = 
    ${env:MY_GIT_REPOS_FOR_AUTO_SYNC}
depth = 1
```
The environment variable settings:

```
SET MY_GIT_REPOS_FOR_AUTO_SYNC=D:\WorkArea\developer\code;d:\temp
```

**Comment by ueffel** [comment]
This kind of configuration is not supported... yet. I see what I can do

**Comment by ueffel** [comment]
It should be working now. Have a look at the new version :)

**Comment by raxuser100** [comment]
absolutely amazing, thaks so much for the epic speedy turnaround, that works perfectly. thanks again
